### ISSUE TITLE
Problem with generics

### ISSUE THREAD

**Issue by alex-caelus** [nikomatsakis/lalrpop#104]
use lalrpop_util::ParseError;

    use generator::Generator;

    grammar<Gen> where Gen: Generator;

    extern {
        type Error = String;
    }

    pub Schema : String = "grammar" "{" <id:r"[a-zA-Z0-9]*"> "}" =>? match Generator::schema(id) {
        Ok(sch) => Ok(sch),
        Err(err) => Err(ParseError::User { error: err })
    };

gives me the following error:

    src\test.rs:29:20: 29:28 error: unable to infer enough type information about `_`; type annotations or generic parameter binding required [E0282]
    src\test.rs:29         match try!(__state0(input, &mut __tokens, __lookahead)) {
                                      ^~~~~~~~
    src\test.rs:29:15: 29:64 note: in this expansion of try! (defined in <std macros>)
    src\test.rs:29:20: 29:28 help: run `rustc --explain E0282` to see a detailed explanation

I've found this previous issue #34 where it was suggested that `__state0(...)` be called like `__state0::<Gen>(...)`. Perhaps that is the necessary fix?

**Comment by nikomatsakis** [comment]
Hmm, yes, I suppose that is necessary.

**Comment by nikomatsakis** [comment]
For the time being you could work around this by introducing a dummy argument of type `std::marker::PhantomData<Gen>`

**Comment by nikomatsakis** [comment]
(I will try to work up a fix shortly though)

**Comment by nikomatsakis** [comment]
This is actually mildly tricky to fix. However, if you update to the newest LALRPOP, the state-table codegen method (now the default) I think avoids the problem here.

The reason it is tricky is that, in recursive ascent mode, we add an extra type parameter (`__TOKENS`) to states, and it's not always clear what value to pass for that -- but if we pass any type parameters, we need to pass that one. It occurs to me that maybe we can do it by passing a `PhantomData

**Comment by nikomatsakis** [comment]
(Ah, no, it won't work there either.)
