### ISSUE TITLE
`process_root` recompiles regardless of whether .lalrpop file has changed

### ISSUE THREAD

**Issue by saghm** [nikomatsakis/lalrpop#107]
I've noticed that if I change one of my the files in my crate, the .lalrpop files seem to get recompiled despite not having been touched. My intuition is that this probably has to do with `process_root` automatically recompiling everything rather than checking the timestamps of the .lalrpop files and the generated Rust files to see which is newer.

Would this be feasible to implement? Obviously this would be a long-term "nice to have" feature, but, well, it *would* be nice to have.

**Comment by TyOverby** [comment]
I can't reproduce this.  lalrpop has always been good about not recompiling for me.

**Comment by Nemikolh** [comment]
I don't have this problem either. Which version of lalrpop are you using?

**Comment by saghm** [comment]
I'm using 0.11.0.

I must be doing something wrong somewhere in project configuration if it works for everyone else. I'll take a look at it later and see if I can track down where the issue is.

Thanks for the quick feedback!

**Comment by nikomatsakis** [comment]
Are you on Windows? I think I had to disable time stamp as the relevant APIs were not stable on Windows, but that is probably no longer true 
On Apr 11, 2016 14:14, Saghm Rossi <notifications@github.com> wrote:I'm using 0.11.0.

I must be doing something wrong somewhere in project configuration if it works for everyone else. I'll take a look at it later and see if I can track down where the issue is.

Thanks for the quick feedback!

**Comment by saghm** [comment]
Nope, I'm actually on Linux.

**Comment by saghm** [comment]
Sorry for leaving this issue open for so long! I actually forgot I had opened it...

I eventually figured out that the lalrpop file was being recompiled because it was importing code from another crate I was developing alongside it, so when I changed some of the code for the things I was importing, the parser had to be regenerated. This is completely expected, I just didn't realize it was occurring. Sorry for bothering everyone about this!
