### ISSUE TITLE
Index out of bounds in try_classify_question

### ISSUE THREAD

**Issue by malleusinferni** [nikomatsakis/lalrpop#194]
On [line 544 in error.rs](https://github.com/nikomatsakis/lalrpop/blob/7af013e7bbe1ce1cc824bd1b7124c1b5a7dfb321/lalrpop/src/lr1/error/mod.rs#L544), LALRPOP tries to index into `action_examples`. If this slice is empty (which I guess normally shouldn't happen) the build script panics.

I assume this function was only called in the first place because my grammar is malformed. Unfortunately I can't share it here. If you need a minimized test case I'll try to put one together.

**Comment by nikomatsakis** [comment]
cc @Marwes

**Comment by sgodwincs** [comment]
I am getting the same error. In my WebIDL parser project, I get the error when I uncomment the following lines in my grammar: [grammar.larlpop#L396](https://github.com/sgodwincs/webidl-rs/blob/master/src/parser/grammar.lalrpop#L396)

It's not a great example since the grammar is large, but I'm assuming it's a conflict since `ExtendedAttributeOther` can match against all the commented lines. Though I'm not really sure how to get around it.

**Comment by nikomatsakis** [comment]
Thanks for the add'l reference. I haven't had time to investigate, will try to do so very soon!

**Comment by malleusinferni** [comment]
I never managed to construct a test case, but this should have been fixed by #259, so I'll go ahead and close it.
