### ISSUE TITLE
Allow reference &str variables in <expr: REGEX>.

### ISSUE THREAD

**Issue by hicqu** [nikomatsakis/lalrpop#217]
Hi, I want to write something like this:
```rust
use other_mod::EXPR_RE;       // const EXPR_RE: &'static str = r"hello world";
Expr: Expr = {
    <s: EXPR_RE> => {    // use a variable here!
        build_Expr_from_str(s)
    }，
};
```

But that's not works. So, do you think support that is a good idea?

**Comment by j16r** [comment]
You can achieve something similar with the `match` expression, e.g:

```rust
match {
  r"hello world" => EXPR_RE,
} else {
  _
}

Expr: Expr = {
    <s: EXPR_RE> => {
        build_Expr_from_str(s)
    }，
};
```

There is an explanation in example `calculator2b`.

**Comment by nikomatsakis** [comment]
@hicqu I'm not quite sure I understand; you want the string constant to be determined by some other Rust code, is that it? If so, I think that's unlikely to be something we ever support, or at least not without some other mode, since it would prevent us from analyzing the tokens statically.

However, you could do this:

```rust
use other_mod::EXPR_RE;       // const EXPR_RE: &'static str = r"hello world";
Expr: Expr = {
    <s: r"\w+"> =>? {    // match all identifiers or whatever
        if s  == EXPR_RE { Ok(build_Expr_from_str(s)) } else { Err(...) }
    }，
};
```

This would always trigger for any string, but it would then use LALRPOP's "faillible action" rules (that's what `=>?` means) to possibly trigger a parse error if the string didn't fit what you expected. Maybe that helps?

**Comment by hicqu** [comment]
Yes, this is what I want. 

BTW, get new skill **faillible action(=>?)** which is very helpful for me. 👍
