### ISSUE TITLE
Unittesting private Non-Terminals

### ISSUE THREAD

**Issue by ekiwi** [nikomatsakis/lalrpop#237]
I am currently writing a grammar from the bottom up and would like to add some unittests for all new non terminals that I add. However, I do not want all of these non-terminals to be part of the public API.

What is the recommended way of solving this?
From what I have gathered, for normal Rust code, you would just add the unittests to the same file in order to test private functions. But that is not possible for the grammar definitions, correct?
Is there a way to make non-terminals only public when building tests?

**Comment by wieczyk** [comment]
I am not sure if it is possible to get access to functions, which not came from `pub` nonterminals. I think lalrpop generates entry-point functions only for those marked variables.

Maybe you would be interested in this approach: For sake of testability I am marking many nonterminals as public and I am introducing small wrapper around generated parser. The wrapper is only a facade which delegates tasks to generated parser, but the wrapper is part of public API while generated parser is not. 

For example, assume that we have some main variables like `statement`, `expression`, `declaration`, `module`.  I would mark all of them as public and I would use them in unit tests. Since those tests are part of my project/library/crate it is OK. The facade would had wrapper only for `module` parsing function, so end-user would NOT get access to rest of parser entry points. 

It is quite easy to implement in rust.

```
./parser/                      parser module
./parser/mod.rs                main file where you have "mod grammar" and "mod test" and facade could be implemented there
./parser/test.rs               tests
./parser/grammar.lalrpop       lalrpop input file
./parser/grammar.rs            generated parser
```

Additional benefit of the facade is that you could make some usable wrappers for selected entry points. Like wrapper which opens file and reads buffer and then executed parser on it.

This approach does not allow you to make unit tests for all nonterminals, but I am not sure if it is good idea to test parser in that way. Set of nonterminals is quite technical part of parser and introducing unit tests for most of them could make your parser hard to develop. I think this topic touches a philosophy of testing. Developers in one company for which I worked were crazy about unit tests and we had a rule that everything had to be unit tested. In long term it gave a thousands of tests, but I doubt if most of them were valuable. When I wanted to change something then I had to spend a lot of effort for aligning tests (when people were perpetually forced to align test then they started to be less careful). When I wanted to refactor something I had actually also to refactor tests (so tests were not valuable in the most dangerous situation). Today I think it is bad to have such rule/idea to tests everything by structural tests. I prefer to make module tests (I mean a tests which are less coupled with structure of code or are coupled at higher level) and use more detailed testing only in places where I know it is worth do it.

If you have variables like `call_expression`, `assign_statement`, `function_definition`, ... then you could actually use those more generic entry points like `statement`, `expression`, `definition` to make tests for them. It is how I am doing it. In case where I want to change structure of my grammar (extend it or refactor) I still have valuable tests.

**Comment by nikomatsakis** [comment]
@wieczyk is correct that LALRPOP requires knowing what is the "starting point" for the grammar -- basically, for each `pub` non-terminal, we will generate an independent parser that is specialized to using that particular non-terminal as the starting point. We have to have a unique starting symbol, I'm afraid.

I think what I would do in your shoes is to make a "meta-nonterminal" like:

```rust
pub test: Test = {
    "foo" <Foo> => Test::Foo(<>),
    "bar" <Bar> => Test::Bar(<>),
};
```

then you can write unit tests that supply as input stuff like "foo ..." where `...` is whatever a `Foo` consists of. Kind of boilerplate-y, but it would result in exactly one "test" parser that contains all nonterminals, along with (presumably) one *real* parser.

**Comment by ekiwi** [comment]
Thank you for the suggestions! I will investigate both once I get time to continue working on this project. Great parser generator, @nikomatsakis!
