### ISSUE TITLE
Failure to parse acceptable term.

### ISSUE THREAD

**Issue by mthom** [nikomatsakis/lalrpop#242]
Hello,

I'm writing a Prolog interpreter that uses LALRPOP to parse Prolog programs. The grammar is here:

https://github.com/mthom/rusty-wam/blob/master/src/prolog/prolog_parser.lalrpop

I'm trying to parse the following Prolog term:

`f(call(p, q)).`

I have a rule called `<Call>` that matches on the string "call". When `<Call>` is removed, the term parses successfully. With `<Call>` in place, parse_TopLevel returns the error

`UnrecognizedToken { token: Some((2, (13, "call"), 6)), expected: ["\"[\"", "\"[]\"", "\"_\"", "r#\"[A-Z][A-Za-z0-9_]*\"#", "r#\"[a-z][A-Za-z0-9_]*\"#"] }`

I think this is a bug.

**Comment by nikomatsakis** [comment]
Question: When you have a token `"call"` in the LALRPOP, it takes precedence over regular expressions -- it is effectively a **keyword**. Could this be your problem?

(Sorry for the delay in response! Been overwhelmed lately.)

**Comment by mthom** [comment]
I'm not sure. I've stepped through the generated parser code in gdb. The `<Call>` rule is attempted first, but it's only valid for "call" being the atom of a top level term. It fails to backtrack and match against `<Term>` -- shouldn't that be what happens?

**Comment by nikomatsakis** [comment]
@mthom Well, first off, when parsing in an LR parser, there is no notion of doing something "first". If parser generation succeeds, then the grammar must be ambiguous, and hence there is only one correct order in which to parse things. I think the problem is indeed that `"call"` (in LALRPOP) is considered a *keyword*, which means that it takes precedence over regular expressions. It looks though like you've modified the grammar in the meantime, so it's hard to be sure.

**Comment by mthom** [comment]
Yes, I think that should work. I will close the issue. Thanks very much.
